{% set name = "json-repair" %}
{% set version = "0.61.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name|replace("-", "_") }}-{{ version }}.tar.gz
    sha256: a3754543f050093efcda6c9ab00b20a236b5d082c8c622bc65b88fa74ff8d51f
  - url: https://github.com/mangiucugna/{{ name|replace("-", "_") }}/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 5f5d4dcef3b590074a49a2d646975bed336d9ba7253600a7971d76468367d407
    folder: gh_src

build:
  number: 0
  skip: true  # [py<310]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python
    - setuptools >=61.0
    - wheel
  run:
    - python
  run_constrained:
    - jsonschema >=4.21
    - pydantic >=2

# fixture 'benchmark' not found
{% set ignore_tests = "--ignore=gh_src/tests/test_performance.py" %}
{% set deselect_tests = "" %}
# PermissionError: [WinError 32] The process cannot access the file because it is being used by another process
{% set deselect_tests = deselect_tests + " --deselect=gh_src/tests/test_repair_json_cli.py::test_cli" %}  # [win]

test:
  source_files:
    - gh_src/src
    - gh_src/tests
  imports:
    - json_repair
  requires:
    - pip
    - pytest
    - jsonschema
  commands:
    - pip check
    - PYTHONPATH=gh_src pytest -v gh_src/tests {{ ignore_tests }} {{ deselect_tests }}  # [not win]
    - set PYTHONPATH=gh_src && pytest -v gh_src/tests {{ ignore_tests }} {{ deselect_tests }}  # [win]

about:
  home: https://github.com/mangiucugna/json_repair
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A package to repair broken json strings
  description: A package to repair broken json strings
  doc_url: https://github.com/mangiucugna/json_repair
  dev_url: https://github.com/mangiucugna/json_repair

extra:
  recipe-maintainers:
    - jan-janssen
